/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FeedbRouteImport } from './routes/feedb'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AbtRouteImport } from './routes/abt'
import { Route as IndexRouteImport } from './routes/index'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbRoute = FeedbRouteImport.update({
  id: '/feedb',
  path: '/feedb',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AbtRoute = AbtRouteImport.update({
  id: '/abt',
  path: '/abt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abt': typeof AbtRoute
  '/contact': typeof ContactRoute
  '/feedb': typeof FeedbRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abt': typeof AbtRoute
  '/contact': typeof ContactRoute
  '/feedb': typeof FeedbRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abt': typeof AbtRoute
  '/contact': typeof ContactRoute
  '/feedb': typeof FeedbRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abt' | '/contact' | '/feedb' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abt' | '/contact' | '/feedb' | '/projects'
  id: '__root__' | '/' | '/abt' | '/contact' | '/feedb' | '/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbtRoute: typeof AbtRoute
  ContactRoute: typeof ContactRoute
  FeedbRoute: typeof FeedbRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedb': {
      id: '/feedb'
      path: '/feedb'
      fullPath: '/feedb'
      preLoaderRoute: typeof FeedbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abt': {
      id: '/abt'
      path: '/abt'
      fullPath: '/abt'
      preLoaderRoute: typeof AbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbtRoute: AbtRoute,
  ContactRoute: ContactRoute,
  FeedbRoute: FeedbRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
